[package]
name = "mod-community"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
tokio = { version = "1.27", features = ["full"] }
async-graphql = "5.0"
async-graphql-axum = "5.0"
